-- Day 4: SQL Interview-Style Questions

-- Show all customers from London.
SELECT *
FROM customers
WHERE city = 'London';

-- Show products costing more than 100.
SELECT *
FROM products
WHERE price > 100;

-- Calculate total revenue generated by each product.
SELECT 
    p.product_name, 
    SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN products p 
    ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- Count how many orders each customer placed.
SELECT 
    c.customer_id, 
    c.customer_name, 
    COUNT(o.order_id) AS number_of_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id 
GROUP BY c.customer_id, c.customer_name
ORDER BY c.customer_id ASC;

-- Categorise products by price using CASE.
SELECT 
    product_name,
    price,
    CASE
        WHEN price > 200 THEN 'Expensive'
        WHEN price BETWEEN 50 AND 200 THEN 'Moderate'
        WHEN price < 50 THEN 'Cheap'
    END AS price_category
FROM products;

-- Find the customer who spent the most money.
SELECT 
    c.customer_name, 
    SUM(o.quantity * p.price) AS total_spent
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id 
JOIN products p
    ON p.product_id = o.product_id
GROUP BY c.customer_name 
ORDER BY total_spent DESC
LIMIT 1;

-- Show revenue generated by each city.
SELECT 
    c.city, 
    SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id 
JOIN products p
    ON p.product_id = o.product_id
GROUP BY c.city 
ORDER BY total_revenue DESC;

-- Find the average value of all orders.
SELECT 
    AVG(o.quantity * p.price) AS average_order_value
FROM orders o
JOIN products p
    ON o.product_id = p.product_id;

-- Find the most frequently ordered product by quantity sold.
SELECT 
    p.product_name, 
    SUM(o.quantity) AS total_quantity
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_quantity DESC
LIMIT 1;

-- Return only customers whose total spending exceeds 200.
SELECT 
    c.customer_name, 
    SUM(o.quantity * p.price) AS total_spent
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id 
JOIN products p
    ON p.product_id = o.product_id
GROUP BY c.customer_name
HAVING SUM(o.quantity * p.price) > 200
ORDER BY total_spent DESC;
